url: "https://codonaft.i2p"
theme_settings:
  upstream_url: "https://codonaft.com"
  p2p_player:
    media_urls:
    - http://codnaft43k7ncna2hfsxrzi2nqoxieu22vbyjkmhkwdrrta2ghlq.b32.i2p
    upstream_media_urls:
    - https://media.codonaft.com
    - https://media-cached.codonaft.com
